on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: link reactbunode
      run: bun link
      working-directory: packages/ReactBunode

    - name: Build
      run:  bun install && bun link reactbunode && bun run build
      working-directory: packages/docs
    - name: Publish
      uses: cloudflare/pages-action@1
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        projectName: reactbunode # e.g. 'my-project'
        directory: packages/docs/.reactbunode/prd
        gitHubToken: ${{ secrets.GITHUB_TOKEN }}
